### ISSUE TITLE
horrible white noise with some sounds

### ISSUE THREAD

**Issue by maxlefou** [NagyD/SDLPoP#137]
When I play, I get some horrible loud white noise sound at some times: 
- when gates are opening
- when gates are closing abruptly
- when the prince lands softly on floor
- when falling floor breaks down
- when spikes activates

Haven't went further but the other sound effects are strangely fine.

**Comment by NagyD** [comment]
Which version of SDL are you using?
Older versions of SDL have a known bug that causes this.
See here: https://github.com/NagyD/SDLPoP/blob/master/doc/Readme.txt#L312

@Falcury: Do you think I should add some code that detects this bug?
People keep being bitten by this bug, even though [it was fixed 2 years ago](https://bugzilla.libsdl.org/show_bug.cgi?id=2389). (By me...)
See #126 and #64.

**Comment by Falcury** [comment]
> @Falcury: Do you think I should add some code that detects this bug?
> People keep being bitten by this bug, even though it was fixed 2 years ago. (By me...)
> See #126 and #64.

Yes, I think that would be a good idea!
My own suggestion would be to simply check the version number. 
But that's only because I can't think of an easy way to check whether the bug actually occurs. You fixed the bug yourself, maybe you already know a way to do it?

**Comment by NagyD** [comment]
@maxlefou: Please check whether the newest commits fixed the bug for you.

**Comment by vanfanel** [comment]
@NagyD : I am also seing this. I am using SDL 2.0.6, which is the latest stable SDL2 version.
Exactly the same sounds thah @maxlefou listed, have an horrible crackling sound.
I am trying the latest commits from here, so it's not fixed :(

**Comment by NagyD** [comment]
> I am also seeing this. I am using SDL 2.0.6, which is the latest stable SDL2 version.

I am also having a sound problem with SDL 2.0.6, although it's somewhat different: http://forum.princed.org/viewtopic.php?p=22005#p22005

> I have forced "desired_audioformat = AUDIO_U8" in the code even if my SDL2 version is 2.0.6, and the problem still persists,

Did you also try channels=1 instead of 2? (Together with the U8 audioformat.)

What about SDL 2.0.5, does it produce this bug for you?
If it doesn't then you should use that, at least until we sort this out.

By the way, @maxlefou commented on September 21th, but [SDL 2.0.6 was released on September 22th](https://discourse.libsdl.org/t/sdl-2-0-6-released/23109).

**Comment by vanfanel** [comment]
@NagyD : I have tried "channels=1" and the same loud crackling is still there.
About SDL 2.0.5, I have tried SDLPoP against it, and the crackling sound is **not** present, so it's a 2.0.6 problem for sure.

**Comment by Falcury** [comment]
> I think it may be related to SDL2_Mixer and not SDL2 directly, because other old games reimplementations using it have similar problems here, like rawgl.

@vanfanel: Some time ago I made a branch where I replaced SDL2_mixer with stb_vorbis.c: https://github.com/Falcury/SDLPoP/tree/stbv
If you want to rule out SDL2_mixer as a cause, maybe you could check out that branch and see if that fixes the problem. If the problem persists, then SDL2 2.0.6 itself should be at fault.

**Comment by vanfanel** [comment]
@Falcury : I have tried your stbv branch, and crackling still persists, so well, it's SDL2 itself to blame...
I believe it's the resampling routines, so SDL_ConvertAudio() is doing something wrong under the hood. On your stbv branch, you call SDL_ConvertAudio() directly.

The good thing about yout stvb branch is that SDL_BuildAudioCVT() is also called directly, so I can take it out of play_digi_sound() and call it at the end of init_digi() instead, just one time.
That's very good because, on some slow platforms like the Raspberry Pi, SDL_BuildAudioCVT() takes a great amount of time to return, so calling it *just once* on init_digi() prevents noticeable pauses on the game. So, can you move the SDL_BuildAudioCVT() call to init_digi() in your stbv branch, please?
The same SDL_AudioCTV can be reused as many times as needed, no need to re-create it on every digi-sound play.

**Comment by NagyD** [comment]
> The good thing about yout stvb branch is that SDL_BuildAudioCVT() is also called directly, so I can take it out of play_digi_sound() and call it at the end of init_digi() instead, just one time.

But one of the parameters for SDL_BuildAudioCVT is the original sample rate of the current sound.
What do you pass in to that parameter in your case?

**Comment by vanfanel** [comment]
I do:

`       int result = SDL_BuildAudioCVT(&cvt,
                AUDIO_U8, 1, 11000,
                digi_audiospec->format, digi_audiospec->channels, digi_audiospec->freq
        );
`

at the end of init_digi(), and it works fine :)

**Comment by NagyD** [comment]
Most sounds have 11000 Hz sample rate, so I guess it should work...
(List of sample rates of PoP1 sounds: http://forum.princed.org/viewtopic.php?p=14592#p14592)

To return to on-topic: There have been some recent changes in the SDL resampling code [(like this one)](https://bugzilla.libsdl.org/show_bug.cgi?id=3851).
Does the [latest SDL source from the repo](https://libsdl.org/hg.php) fix the noise you hear in SDL 2.0.6?

**Comment by vanfanel** [comment]
@NagyD : Yes, I tried latest SDL2 and the problem is still there. It's not the only game showing it here on ARM, so a separate issue has been opened and issue reproduced by the main SDL2 developers:

https://bugzilla.libsdl.org/show_bug.cgi?id=3876

About SDL_BuildAudioCVT() and the samplerate list: there's still a couple of samples (skell alive.wav and res10015.bin) that seem to be not 11000Hz. Maybe they ALL could be converted to the "standard" 11025 rate?

**Comment by NagyD** [comment]
It seems your bug was fixed.
Now the question is, was this the same thing that the OP complained about?
He didn't comment anything since he reported the bug.

**Comment by vanfanel** [comment]
Yes, I think all audio problems are solved now. I wouldn't worry anymore :)
